- name: Configure hosts
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: bootstrap

- name: Install monitor agent
  hosts: agent
  become: yes
  become_method: sudo
  serial: 0
  roles:
    - role: agents

- name: Install monitor server
  hosts: server
  become: yes
  become_method: sudo
  serial: 0
  gather_facts: True
  roles:
    - role: server
